module.exports={
ui:{
 docTitle:"The Mike Case: simulación de liderazgo",
 brand:"Simulación de liderazgo",
 introTag:"Una simulación de liderazgo",
 introTitle:"The Mike Case",
 introLead:"Lideras un equipo de ocho personas. Mike es senior, gracioso y querido, y, sin proponérselo, hace más difícil que las voces más nuevas se escuchen. Lo que hagas al respecto define qué cree tu equipo que es seguro decir en voz alta.",
 fwNote:"Cada decisión se evalúa según el adidas Leadership Framework. La seguridad psicológica no es una habilidad aislada: es el resultado de practicar estos pilares de forma consistente. Como esto afecta directamente el desempeño del equipo, <b>Deliver Results</b> también se evalúa aquí, junto con Empower y Elevate.",
 introFoot:"6 decisiones. La mayoría no tiene una opción claramente perfecta: líderes razonables elegirían distinto. Al final recibes un perfil y un pilar en el que enfocarte para la discusión grupal.",
 resultNote:"Tu perfil surge de tu desempeño en los seis pilares de abajo: la seguridad psicológica es el resultado de una conducta de liderazgo consistente, no una habilidad aislada.",
 planTitle:"Tu plan de acción de seguridad psicológica"
},
excel:[
 {w:"Conecta el trabajo del equipo con el propósito, los productos, los consumidores y la cultura de adidas, en las decisiones y no solo en las palabras.",a:"¿Siento más conexión con adidas por la forma en que mi líder se muestra?"},
 {w:"Asume una responsabilidad real, equilibrando el impacto en el negocio, las personas y las consecuencias de largo plazo.",a:"¿Mi líder se hace cargo de las decisiones y los resultados incluso cuando es incómodo?"},
 {w:"Mira hacia adelante, cuestiona la forma actual de trabajar y crea espacio para mejores soluciones.",a:"¿Mi líder nos ayuda a mirar hacia adelante, o mayormente reaccionamos a la demanda del día a día?"}
],
scored:{
 inclusion:"Crea un entorno donde las distintas perspectivas se valoran e incluyen de verdad.",
 engage:"Da una dirección clara y una energía que ayudan a las personas a hacer su mejor trabajo.",
 develop:"Apoya activamente el crecimiento con feedback, confianza y oportunidades.",
 results:"Ayuda a convertir los objetivos en resultados enfocándose en lo que realmente crea valor.",
 accountability:"Fija expectativas claras y aborda los problemas de forma constructiva.",
 grow:"Es ejemplo de aprendizaje y de apertura al feedback."
},
phases:[
{title:"El comentario",
 narrative:[
  "Tu equipo va por la mitad de la reunión semanal. Alex, que se sumó hace dos meses, propone un nuevo enfoque para el onboarding de clientes: algo verde todavía, pero prometedor.",
  "Mike, un ingeniero senior, se ríe y se reclina en la silla: <em>“En realidad eso ya lo probamos hace años”</em>, dice sonriendo. Algunos se ríen con él.",
  "Todavía en tono amable, agrega: <em>“Supongo que cada persona nueva tiene que redescubrir nuestros viejos errores.”</em> Alex también sonríe, pero la sonrisa no le llega a los ojos. No vuelve a hablar en el resto de la reunión.",
  "Fue un comentario rápido, hasta un poco gracioso. Tienes unos dos segundos para decidir si vale la pena frenar la reunión por eso."],
 choices:[
 {l:"Reírte con los demás y seguir adelante",
  t:"Mike cae bien y, técnicamente, fue un chiste. Señalarlo podría convertirte en quien le corta la energía a la sala.",
  imm:"La reunión sigue sin sobresaltos. Mike se siente respaldado. Alex no dice nada más en el resto de la reunión.",
  del:"En las semanas siguientes, los aportes de Alex en las reuniones caen casi por completo, aunque es difícil afirmar con certeza que sea por esto.",
  why:"Esto mantiene la reunión liviana y no convierte un chiste menor en un tema mayor: un instinto defendible en el momento. El costo es que, en tiempo real, no puedes saber si fue algo inofensivo o la primera ficha del dominó."},
 {l:"Nombrarlo con respeto, ahí mismo",
  t:"“Mike, sé que no fue con mala intención, pero asegurémonos de que las ideas nuevas tengan una escucha justa, más allá de lo que hayamos probado antes. Alex, ¿puedes contarnos qué sería distinto esta vez?”",
  imm:"La sala queda en silencio un segundo. Mike parece sorprendido, pero asiente: “Tienes razón.” Alex, con dudas, sigue explicando.",
  del:"En las semanas siguientes, otros se animan un poco más a hablar, aunque Mike también parece algo más reservado contigo.",
  why:"Nombrarlo en el momento protege a Alex y marca, en tiempo real, qué es aceptable. También implica corregir a un colega querido frente a todo el equipo por lo que, a primera vista, fue un comentario menor."},
 {l:"Quedarte en silencio y hacer avanzar la discusión",
  t:"“Buen punto. Escuchemos también al resto del equipo.” Rediriges sin nombrar el comentario, con la idea de observar si se repite.",
  imm:"La reunión sigue sin fricción. Nadie parece notar que pasó algo.",
  del:"Alex habla un poco menos en las reuniones siguientes. No sabes si tiene relación.",
  why:"Mantener la reunión en movimiento evita convertir un comentario en una confrontación y te da margen para observar antes de reaccionar. El riesgo es que, desde el lugar de Alex, observar y no darse cuenta se ven exactamente igual."}]},

{title:"Mike interrumpe otra vez",
 narrative:[
  "Dos semanas después. Alex le está explicando al equipo la solución a un bug recurrente. En mitad de la frase, Mike interviene: <em>“En realidad, creo que el camino más rápido es parchearlo en la capa de la API.”</em>",
  "Alex deja de hablar. Técnicamente Mike no se equivoca, incluso podría ser la mejor solución. Pero es la segunda vez este mes que interrumpe a Alex antes de que termine una idea. Nadie más parece notarlo.",
  "Tienes unos tres segundos para decidir qué haces, si es que haces algo, frente a todo el equipo."],
 choices:[
 {l:"Señalarlo de inmediato, en la sala",
  t:"“Espera, Mike. Deja que Alex termine la idea primero.”",
  imm:"La sala queda en silencio. Alex termina, con algo de nervios. Mike levanta las manos: “Perdón, perdón, sigue.”",
  del:"Alex parece participar con más seguridad en las reuniones siguientes. Mike está notablemente más callado en lo que queda de esta.",
  why:"Corregirlo en vivo protege el momento para Alex y le muestra a todo el equipo qué se espera. También implica corregir a un colega senior y querido frente al grupo por una sugerencia técnica que ni siquiera era incorrecta."},
 {l:"Dejarlo pasar y hablarlo con Mike en privado apenas termina",
  t:"La reunión continúa. Al terminar, buscas a Mike: “Interrumpiste a Alex dos veces este mes. Dale espacio para terminar.”",
  imm:"La reunión sigue fluida. En privado, Mike recibe el comentario sin mucha reacción: “Anotado, perdón por eso.”",
  del:"Alex nunca ve que la corrección ocurre. Desde su lugar, la reunión se sintió igual que las anteriores.",
  why:"Una conversación privada protege a Mike de la vergüenza pública y mantiene intacta la energía de la reunión. El costo es que Alex nunca ve la corrección, así que la lectura tácita de la sala sobre lo que es aceptable no cambia."},
 {l:"Redirigir de forma neutral sin nombrar lo que pasó",
  t:"“Alex, continúa. Después volvemos al punto de Mike.”",
  imm:"La reunión sigue sin confrontación. Alex termina su idea.",
  del:"La semana siguiente vuelve a pasar algo parecido. Empieza a verse menos como un descuido y más como un hábito específico con Alex.",
  why:"Esto mantiene el ritmo y le da espacio a Alex para terminar sin confrontación. El riesgo es que trata la interrupción como algo incidental y no como un patrón que vale la pena nombrar, así que la norma en realidad no cambia."}]},

{title:"Escribir la evaluación",
 narrative:[
  "Llega la temporada de evaluaciones de desempeño. Tienes que dejar este patrón por escrito como parte de la evaluación formal de Mike: algo que lo va a acompañar y que él va a leer.",
  "Estás evaluando algunas formas de redactarlo. Ninguna se ve claramente mal en el papel, pero cada una tiene una trampa que no vas a ver del todo hasta después de escribirla."],
 choices:[
 {l:"Dejarlo en tus notas privadas de manager, sin decirle a Mike que existe",
  t:"Agregas una nota confidencial en tu propio archivo que marca el patrón como algo a monitorear, sin plantearlo directamente con Mike.",
  imm:"A Mike su evaluación le parece bien. No tiene idea de que se marcó algo.",
  del:"Si esto alguna vez pesa en una decisión de promoción o de bono, Mike no habrá tenido oportunidad de responder a algo que nunca supo que existía.",
  why:"Guardar una nota privada se siente prudente y evita una conversación incómoda antes de sentirte en condiciones de tenerla. Pero documentar algo que puede afectar la carrera de Mike sin decírselo nunca rompe la justicia básica del feedback: no puede mejorar ni cuestionar algo que nunca le dijeron que existe."},
 {l:"Plantearlo como un rasgo general: “necesita desarrollar más paciencia con el talento junior”",
  t:"Escribes la nota en términos generales, sin vincularla a los comentarios o momentos específicos que viste.",
  imm:"Mike la lee y no tiene claro qué cambiar en concreto. “Supongo que voy a intentar ser más paciente.”",
  del:"Sin detalles concretos, es probable que el mismo patrón se repita y que la evaluación del año que viene diga algo parecido, igual de vago.",
  why:"Una nota sobre un rasgo general evita reabrir momentos específicos, posiblemente discutibles, y resulta menos confrontativa de escribir. Pero convertir una conducta en una etiqueta de personalidad no le da a Mike nada concreto sobre lo cual actuar, y el feedback a nivel de carácter es justamente donde la gente se pone a la defensiva en lugar de reflexionar."},
 {l:"Incluir como evidencia un detalle de la conversación privada de Alex contigo, sin dar su nombre",
  t:"Agregas una línea que menciona que “una persona del equipo compartió en privado que se siente silenciada en las reuniones”, lo bastante específica como para que Mike probablemente adivine quién fue.",
  imm:"Mike la lee y, en menos de un día, le pregunta directamente a Alex: “Oye, ¿le dijiste algo de mí a nuestro manager?”",
  del:"Para Alex es una sorpresa desagradable que una conversación privada se haya convertido en evidencia identificable, y ahora desconfía más de volver a contarte algo.",
  why:"Basar el feedback en un momento real y específico es justo lo que lo hace creíble y accionable. El costo aquí es hacerlo de una forma rastreable hasta Alex sin su consentimiento: convierte la confianza que alguien depositó en ti en evidencia que no aceptó aportar, y le enseña a tu equipo que contarte algo no es realmente seguro."}]},

{title:"La conversación difícil",
 narrative:[
  "Le pides quince minutos a Mike. Antes de que puedas abrir la conversación, dice, con una risa relajada: <em>“Si esto es por aquel chiste, creo que la gente se está volviendo un poco demasiado sensible últimamente.”</em>",
  "Después de que planteas tu punto, agrega: <em>“Entendido. La próxima vez voy a tratar de sonar menos experimentado”</em>, con una sonrisa irónica, <em>“pero no estaba tratando de desanimar a nadie.”</em>",
  "Todavía no terminó de atar los cabos. Ya dijiste lo tuyo una vez. Cuánto más vale la pena decir ahora es una decisión realmente difícil."],
 choices:[
 {l:"Mantener el tono cálido, mencionarlo a la ligera y cerrar",
  t:"“Solo es algo para pensar”, dices, y terminas la conversación ahí.",
  imm:"La conversación termina en buen tono. Mike se va con la sensación de haber sido escuchado y no sermoneado.",
  del:"Sin refuerzo, lo que Mike se lleva termina siendo algo más parecido a “ser un poco más amable” que un patrón específico a cambiar.",
  why:"Terminar aquí respeta que ya diste un feedback claro: repetirlo puede sugerir que no confías en que lo haya entendido. El riesgo es que su último comentario sugiere que no terminó de atar los cabos, y estás eligiendo no comprobarlo."},
 {l:"Ir a lo específico (situación, conducta, impacto) y sostener la postura incluso después de su primera respuesta",
  t:"“Entiendo que no estabas tratando de desanimar a nadie, y te creo. Aun así, el impacto existió, más allá de la intención. Eso es lo que necesito que pienses.”",
  imm:"Mike se queda callado un segundo. “Es justo”, dice al fin. No es un cambio total, pero es algo.",
  del:"En las semanas siguientes, Mike es visiblemente más cuidadoso: no es perfecto, pero lo intenta.",
  why:"Separar la intención del impacto le da a Mike algo concreto con lo que trabajar, en lugar de algo de lo que defenderse. El costo es una conversación más larga y menos cómoda, que extiende algo que él parecía querer cerrar."},
 {l:"Hablar del patrón sin rodeos, sin suavizarlo",
  t:"“Mike, esto sigue pasando y tiene que parar. No hay punto medio.”",
  imm:"Mike se tensa. “Está bien... te escucho”, más a la defensiva que reflexivo.",
  del:"El mensaje llega, técnicamente. Pero Mike está más a la defensiva por un tiempo, sin necesariamente entender por qué.",
  why:"La franqueza elimina cualquier ambigüedad sobre la seriedad del tema. El costo es que, sin empatía, es fácil que Mike lo escuche como un ataque y no como información que puede usar."}]},

{title:"Reforzar el mensaje",
 narrative:[
  "Quieres asegurarte de que el cambio se sostenga. Hay tres formas de “fijar” el mensaje. Ninguna es una falta, pero vale la pena notar qué le enseña realmente cada una al equipo."],
 choices:[
 {l:"Resumirlo por escrito y copiar al manager de Mike, “para ser transparente”",
  t:"Envías un correo con el resumen de la conversación y pones en copia al manager de Mike.",
  imm:"El correo sale. Mike responde con cortesía, pero visiblemente sorprendido por quién estaba en copia.",
  del:"Mike empieza a dudar antes de aceptar cualquier conversación informal contigo: ya no sabe qué termina quedando registrado.",
  why:"Esto parece accountability, pero escalar sin avisarle antes a Mike convierte un momento de coaching en una consecuencia sorpresa: rompe la confianza en que una conversación privada seguiría siendo privada y le enseña al equipo que hablar contigo en privado no es realmente privado."},
 {l:"Elogiar públicamente a Mike en la próxima reunión por “escuchar bien”",
  t:"En la reunión siguiente, destacas en público cómo Mike “mejoró su escucha”.",
  imm:"Mike se ve un poco incómodo, pero acepta el elogio. El equipo no termina de entender el contexto.",
  del:"Nadie en el equipo vio a Mike equivocarse en esto en público, así que el elogio se siente fabricado, y el propio Mike no sabe bien cómo interpretarlo la próxima vez.",
  why:"El elogio público se siente generoso, pero fabricar un momento a partir de una corrección privada, sin avisarle a Mike, lo expone por algo que el equipo nunca lo vio hacer bien, y le enseña a la sala que el feedback es teatro y no honestidad."},
 {l:"Pedirle a Alex, delante de Mike, que confirme que ahora las cosas están mejor",
  t:"“Alex, ¿sientes que las cosas mejoraron con Mike?”, preguntas, con Mike presente.",
  imm:"Alex duda, mira a Mike y da una respuesta vaga y positiva.",
  del:"Alex evita mencionar cualquier tema relacionado con Mike durante las semanas siguientes, incluso cuando se lo preguntan en privado.",
  why:"Esto pone a la persona con menos poder de la sala en la posición de tener que avalar públicamente, en el momento, la mejora de su colega senior. Aunque se plantee con amabilidad, convierte la seguridad psicológica de Alex en algo que tiene que actuar frente a un público."}]},

{title:"Cerrar el ciclo",
 narrative:[
  "Un mes después. Mike lleva semanas sin hacer un chiste despectivo y las interrupciones casi desaparecieron. Alex volvió a participar, con cautela.",
  "Es un avance real, no la perfección, y debería verse también en los resultados del equipo, no solo en el clima. Qué hacer ahora con eso es una decisión sobre la que los líderes de verdad no se ponen de acuerdo."],
 choices:[
 {l:"Mantenerlo informal: mencionar las cosas a medida que surgen",
  t:"Decides no formalizar nada y seguir prestando atención como hasta ahora.",
  imm:"Nada cambia en el día a día. Mike no siente que está “en un plan”.",
  del:"El avance se sostiene en general, aunque algunos momentos menores pasan sin abordarse cuando tu atención está en otra parte.",
  why:"Mantenerlo informal conserva el espíritu de una mentoría genuina, acorde con el avance real y voluntario de Mike. La contracara es que depende por completo de tu atención sostenida: nada te obliga a seguir notándolo si tu disponibilidad se reduce."},
 {l:"Ponerlo por escrito: una nota breve de desarrollo con fecha de seguimiento",
  t:"Redactas unas líneas que resumen el patrón, el avance y una fecha de seguimiento, y las compartes directamente con Mike.",
  imm:"Mike la lee con atención. “Entiendo por qué lo escribes. Solo que no esperaba que fuera... oficial.”",
  del:"Las expectativas ahora son inequívocas para ambos, pero la relación cambia un poco: de la mentoría hacia algo más parecido a un proceso.",
  why:"La documentación crea un registro claro y justo que protege tanto a Mike como a Alex si algo reaparece más adelante. El costo es que formalizar antes de lo que Mike considera justificado puede leerse como una escalada y enfriar una relación que iba en la dirección correcta."},
 {l:"Darlo por resuelto y seguir adelante",
  t:"Dada la mejora visible, decides no volver a plantearlo salvo que surja algo nuevo.",
  imm:"No se dice nada. Todos siguen adelante, tú también.",
  del:"Unos meses después, reaparece una versión más silenciosa del patrón original, esta vez con otra persona junior del equipo.",
  why:"El avance real merece reconocimiento, y reabrir constantemente un tema resuelto tiene su propio costo. El riesgo, dado que ya viste este patrón reaparecer en silencio una vez, es tratar “mejor” como si fuera lo mismo que “terminado”."}]}
],
profiles:{
 champion:{name:"Referente de seguridad psicológica",
  sum:"Interviniste de forma consistente con respeto, coraje y especificidad, incluso cuando era incómodo. Es más probable que tu equipo hable, discrepe y tome riesgos gracias a cómo respondiste.",
  str:"Feedback directo y específico. Equilibra empatía con accountability. Da seguimiento en el tiempo.",
  risk:"Cuidado con el desgaste: iniciar conversaciones difíciles de forma constante consume energía real."},
 inconsistent:{name:"Inclusión con inconsistencias",
  sum:"Te importa la inclusión, pero tus respuestas fueron desparejas: a veces valientes y específicas, otras evasivas o vagas. Es probable que tu equipo viva la seguridad como algo que depende de la situación.",
  str:"Interés genuino por el equipo. Capacidad de intervenir con fuerza cuando te comprometes.",
  risk:"La inconsistencia puede confundir más que una vara consistentemente más baja."},
 avoider:{name:"Tendencia a evitar el conflicto",
  sum:"Tiendes a priorizar la comodidad por sobre la intervención directa. Los temas que notaste muchas veces quedaron sin abordar, o se abordaron con demasiada suavidad.",
  str:"Presencia cálida y de bajo conflicto.",
  risk:"Evitar tiene un costo: sin intervención, las voces dominantes desplazan en silencio a las demás."},
 silencer:{name:"Silenciamiento involuntario",
  sum:"A pesar de las buenas intenciones, tus decisiones (reírte con los demás, quedarte en silencio, suavizar el feedback) probablemente reforzaron las mismas dinámicas que desalientan la participación. Es una de las fallas más comunes y menos visibles, y viene de personas que nunca quisieron hacer daño.",
  str:"Sin malicia ni agresividad: un patrón que realmente se puede corregir una vez que se hace visible.",
  risk:"Las personas del equipo pueden desconectarse en silencio en lugar de confrontarte, porque nada de lo que hiciste estuvo abiertamente mal."}
},
plan:{
 CONT:{
  inclusion:"Dar espacio para que las voces más nuevas o más calladas terminen su idea.",
  engage:"Llevar energía y confianza a las conversaciones difíciles en lugar de dejar que se apaguen.",
  develop:"Dar feedback específico y accionable, no solo emocional.",
  results:"Conectar la seguridad psicológica con decisiones técnicas mejores y más rápidas.",
  accountability:"Nombrar conductas específicas directamente con la persona responsable.",
  grow:"Mantener la curiosidad sobre tus propios puntos ciegos."},
 START:{
  inclusion:"Invitar activamente a las personas más calladas del equipo a volver a la conversación.",
  engage:"Usar la tensión como una oportunidad para construir confianza, no solo para atravesarla.",
  develop:"Estructurar el feedback con situación, conducta e impacto.",
  results:"Medir si el silencio de alguien le está costando calidad o velocidad al equipo.",
  accountability:"Tratar los patrones repetidos, y no solo los incidentes aislados, como algo que vale la pena nombrar de forma directa.",
  grow:"Preguntarle a un par de confianza qué podrías estar pasando por alto sobre tu impacto."},
 COMMIT:{
  inclusion:"En la próxima reunión de equipo, voy a notar quién no habló y voy a invitar a esa persona por su nombre.",
  engage:"En la próxima conversación difícil, voy a nombrar lo que la persona hace bien antes de nombrar lo que tiene que cambiar.",
  develop:"Esta semana, voy a dar un feedback usando situación, conducta e impacto.",
  results:"Esta semana, voy a preguntarle al equipo si algún silencio reciente pudo habernos costado una mejor decisión.",
  accountability:"Esta semana, voy a nombrar un patrón que vengo dejando pasar, directamente con la persona involucrada.",
  grow:"Este mes, voy a preguntarle a una persona de confianza qué cree que se me escapa sobre cómo me muestro en las reuniones."},
 DISC:{
  inclusion:"¿Qué hábito concreto haría más fácil que una voz más callada se anime a hablar este mes?",
  engage:"Cuando aparece la tensión, ¿qué podrías hacer para que siga siendo un diálogo y no un sermón o una retirada?",
  develop:"¿Cómo sería dar feedback estructurado todas las semanas, incluso por momentos menores?",
  results:"¿Qué decisión de tu equipo podría haber sido mejor si alguien se hubiera sentido con seguridad para discrepar antes?",
  accountability:"¿Qué patrón vienes dejando pasar porque nombrarlo resultaba incómodo, y cómo sería nombrarlo?",
  grow:"¿A quién podrías preguntarle, este mes, qué cree que se te escapa sobre tu propio impacto en la sala?"}
}
};
