module.exports={
ui:{
 docTitle:"The Mike Case: simulação de liderança",
 brand:"Simulação de liderança",
 introTag:"Uma simulação de liderança",
 introTitle:"The Mike Case",
 introLead:"Você lidera uma equipe de oito pessoas. Mike é sênior, engraçado e querido, e, sem querer, torna mais difícil que as vozes mais novas sejam ouvidas. O que você faz a respeito define o que a sua equipe acredita ser seguro dizer em voz alta.",
 fwNote:"Cada decisão é avaliada com base no adidas Leadership Framework. Segurança psicológica não é uma habilidade isolada: é o resultado desses pilares praticados com consistência. Como isso afeta diretamente o desempenho da equipe, <b>Deliver Results</b> também é avaliado aqui, junto com Empower e Elevate.",
 introFoot:"6 decisões. A maioria não tem uma opção claramente perfeita: líderes razoáveis escolheriam de formas diferentes. No final, você recebe um perfil e um pilar para focar na discussão em grupo.",
 resultNote:"Esta pontuação vem do seu desempenho nos seis pilares abaixo: a segurança psicológica é o resultado de um comportamento de liderança consistente, não uma habilidade isolada.",
 planTitle:"Seu plano de ação de segurança psicológica"
},
excel:[
 {w:"Conecta o trabalho da equipe ao propósito, aos produtos, aos consumidores e à cultura da adidas, nas decisões e não só nas palavras.",a:"Eu sinto mais conexão com a adidas por causa da forma como a minha liderança se apresenta?"},
 {w:"Assume responsabilidade de verdade, equilibrando o impacto no negócio, nas pessoas e as consequências de longo prazo.",a:"A minha liderança assume a responsabilidade pelas decisões e pelos resultados mesmo quando é desconfortável?"},
 {w:"Olha para a frente, questiona a forma atual de trabalhar e cria espaço para soluções melhores.",a:"A minha liderança nos ajuda a olhar para a frente, ou estamos na maior parte do tempo reagindo à demanda do dia a dia?"}
],
scored:{
 inclusion:"Cria um ambiente em que diferentes perspectivas são genuinamente valorizadas e incluídas.",
 engage:"Dá uma direção clara e uma energia que ajudam as pessoas a fazer o seu melhor trabalho.",
 develop:"Apoia ativamente o crescimento por meio de feedback, confiança e oportunidades.",
 results:"Ajuda a transformar metas em resultados, com foco no que realmente gera valor.",
 accountability:"Define expectativas claras e trata os problemas de forma construtiva.",
 grow:"É exemplo de aprendizado e de abertura ao feedback."
},
phases:[
{title:"O comentário",
 narrative:[
  "Sua equipe está na metade da reunião semanal. Alex, que entrou há dois meses, propõe uma nova abordagem para o onboarding de clientes: ainda um pouco crua, mas promissora.",
  "Mike, um engenheiro sênior, dá uma risada e se recosta na cadeira: <em>“Na verdade, a gente já tentou isso anos atrás”</em>, diz, sorrindo. Algumas pessoas riem junto.",
  "Ainda em tom amigável, ele acrescenta: <em>“Acho que toda pessoa nova precisa redescobrir os nossos velhos erros.”</em> Alex também sorri, mas o sorriso não chega aos olhos. Não fala mais nada até o fim da reunião.",
  "Foi um comentário rápido, até um pouco engraçado. Você tem uns dois segundos para decidir se vale a pena interromper a reunião por isso."],
 choices:[
 {l:"Rir junto e seguir em frente",
  t:"Mike é querido e, tecnicamente, foi uma piada. Apontar isso pode fazer de você a pessoa que derruba a energia da sala.",
  imm:"A reunião segue tranquila. Mike se sente validado. Alex não diz mais nada até o fim da reunião.",
  del:"Nas semanas seguintes, as contribuições de Alex nas reuniões caem quase por completo, embora seja difícil afirmar com certeza que o motivo é esse.",
  why:"Isso mantém a reunião leve e não transforma uma piada pequena em algo maior: um instinto defensável no momento. O custo é que, em tempo real, você não tem como saber se foi algo inofensivo ou a primeira peça do dominó."},
 {l:"Nomear com respeito, ali mesmo",
  t:"“Mike, sei que não foi por mal, mas vamos garantir que ideias novas sejam ouvidas de forma justa, independentemente do que já tentamos antes. Alex, pode contar mais sobre o que seria diferente desta vez?”",
  imm:"A sala fica em silêncio por um segundo. Mike parece surpreso, mas concorda: “Justo.” Alex, com hesitação, continua explicando.",
  del:"Nas semanas seguintes, outras pessoas ficam um pouco mais dispostas a falar, embora Mike também pareça um pouco mais reservado com você.",
  why:"Nomear na hora protege Alex e sinaliza, em tempo real, o que é aceitável. Também significa corrigir um colega querido na frente de toda a equipe por algo que, à primeira vista, foi um comentário pequeno."},
 {l:"Ficar em silêncio e fazer a discussão avançar",
  t:"“Bom ponto. Vamos ouvir também o restante da equipe.” Você redireciona sem nomear o comentário, planejando observar se vira um padrão.",
  imm:"A reunião segue sem atrito. Ninguém parece notar que algo aconteceu.",
  del:"Alex fala um pouco menos nas reuniões seguintes. Você não sabe se tem relação.",
  why:"Manter a reunião andando evita transformar um comentário em confronto e dá a você espaço para observar antes de reagir. O risco é que, do ponto de vista de Alex, observar e não perceber parecem exatamente a mesma coisa."}]},

{title:"Mike interrompe de novo",
 narrative:[
  "Duas semanas depois. Alex está explicando à equipe a correção de um bug recorrente. No meio da frase, Mike entra: <em>“Na verdade, acho que o caminho mais rápido é só aplicar um patch na camada da API.”</em>",
  "Alex para de falar. Tecnicamente, Mike não está errado, pode até ser a melhor correção. Mas é a segunda vez neste mês que ele corta Alex antes do fim de um raciocínio. Ninguém mais parece notar.",
  "Você tem uns três segundos para decidir o que faz, se é que faz alguma coisa, na frente de toda a equipe."],
 choices:[
 {l:"Apontar na hora, na sala",
  t:"“Espera, Mike. Deixa Alex terminar o raciocínio primeiro.”",
  imm:"A sala fica em silêncio. Alex termina, com um pouco de nervosismo. Mike levanta as mãos: “Desculpa, desculpa, pode continuar.”",
  del:"Alex parece participar com mais segurança nas reuniões seguintes. Mike fica visivelmente mais calado no restante desta.",
  why:"Corrigir ao vivo protege o momento para Alex e mostra a toda a equipe o que se espera. Também significa corrigir um colega sênior e querido na frente do grupo por uma sugestão técnica que nem estava errada."},
 {l:"Deixar passar e falar com Mike em particular logo depois",
  t:"A reunião continua. Depois, você procura Mike: “Você cortou Alex duas vezes neste mês. Deixe espaço para a conclusão do raciocínio.”",
  imm:"A reunião segue fluida. Em particular, Mike recebe o recado sem muita reação: “Anotado, desculpa por isso.”",
  del:"Alex nunca vê a correção acontecer. Do ponto de vista de Alex, a reunião foi igual às anteriores.",
  why:"Uma conversa em particular protege Mike do constrangimento público e mantém a energia da reunião. O custo é que Alex nunca vê a correção acontecer, então a leitura implícita da sala sobre o que é aceitável não muda."},
 {l:"Redirecionar de forma neutra, sem nomear o que aconteceu",
  t:"“Alex, continue. Depois voltamos ao ponto do Mike.”",
  imm:"A reunião segue sem confronto. Alex conclui o raciocínio.",
  del:"Algo parecido acontece de novo na semana seguinte. Começa a parecer menos um deslize e mais um hábito específico com Alex.",
  why:"Isso mantém o ritmo e dá espaço para Alex terminar sem confronto. O risco é tratar a interrupção como algo pontual, e não como um padrão que vale a pena nomear, então a norma em si não muda."}]},

{title:"Escrevendo a avaliação",
 narrative:[
  "Chega a época das avaliações de desempenho. Você precisa registrar esse padrão por escrito como parte da avaliação formal de Mike: algo que vai acompanhá-lo e que ele vai ler.",
  "Você está avaliando algumas formas de redigir isso. Nenhuma parece claramente errada no papel, mas cada uma tem uma armadilha que você só vai enxergar por completo depois de escrever."],
 choices:[
 {l:"Manter nas suas anotações privadas de gestão, sem contar a Mike que isso existe",
  t:"Você adiciona uma nota confidencial ao seu próprio arquivo, sinalizando o padrão como algo a monitorar, sem levar o assunto diretamente a Mike.",
  imm:"Para Mike, a avaliação parece tranquila. Ele não faz ideia de que algo foi sinalizado.",
  del:"Se isso algum dia pesar em uma decisão de promoção ou bônus, Mike não terá tido chance de responder a algo que nunca soube que existia.",
  why:"Manter uma nota privada parece cauteloso e evita uma conversa desconfortável antes de você se sentir em condições de tê-la. Mas documentar algo que pode afetar a carreira de Mike sem nunca contar a ele quebra a justiça básica do feedback: ele não pode melhorar nem contestar algo que nunca lhe disseram que existe."},
 {l:"Enquadrar como um traço geral: “precisa desenvolver mais paciência com talentos juniores”",
  t:"Você escreve a nota em termos gerais, sem ligá-la aos comentários ou momentos específicos que presenciou.",
  imm:"Mike lê e não tem certeza do que, especificamente, deve mudar. “Acho que vou tentar ser mais paciente.”",
  del:"Sem detalhes concretos, o mesmo padrão provavelmente vai se repetir, e a avaliação do ano que vem pode dizer algo parecido, com a mesma vagueza.",
  why:"Uma nota sobre um traço geral evita reabrir momentos específicos, possivelmente contestáveis, e é menos confrontadora de escrever. Mas transformar um comportamento em rótulo de personalidade não dá a Mike nada concreto sobre o que agir, e o feedback sobre caráter é justamente onde as pessoas ficam na defensiva em vez de refletir."},
 {l:"Incluir como evidência um detalhe da conversa privada de Alex com você, sem citar o nome",
  t:"Você acrescenta uma linha dizendo que “uma pessoa da equipe compartilhou em particular que se sente silenciada nas reuniões”, específica o bastante para Mike provavelmente adivinhar quem foi.",
  imm:"Mike lê e, em menos de um dia, pergunta diretamente a Alex: “Ei, você falou alguma coisa sobre mim para a nossa liderança?”",
  del:"Para Alex, é uma surpresa desagradável que uma conversa privada tenha virado evidência identificável, e agora há mais receio de voltar a confiar algo a você.",
  why:"Basear o feedback em um momento real e específico é exatamente o que o torna crível e acionável. O custo aqui é fazer isso de um jeito rastreável até Alex, sem consentimento: transforma a confiança que alguém depositou em você em evidência que a pessoa não concordou em fornecer, e ensina à sua equipe que confiar algo a você não é realmente seguro."}]},

{title:"A conversa difícil",
 narrative:[
  "Você pede quinze minutos a Mike. Antes que você consiga abrir a conversa, ele diz, com uma risada tranquila: <em>“Se é sobre aquela piada, acho que as pessoas estão ficando um pouco sensíveis demais ultimamente.”</em>",
  "Depois que você expõe o seu ponto, ele acrescenta: <em>“Entendido. Da próxima vez vou tentar soar menos experiente”</em>, com um sorriso irônico, <em>“mas eu não estava tentando desanimar ninguém.”</em>",
  "Ele ainda não ligou todos os pontos. Você já disse o que tinha a dizer uma vez. O quanto mais vale a pena dizer agora é uma decisão realmente difícil."],
 choices:[
 {l:"Manter o tom leve, mencionar de passagem e encerrar",
  t:"“É só algo para pensar”, você diz, e encerra a conversa ali.",
  imm:"A conversa termina em clima tranquilo. Mike sai com a sensação de ter sido ouvido, e não de ter levado um sermão.",
  del:"Sem reforço, o que fica para Mike é algo mais próximo de “ser um pouco mais gentil” do que um padrão específico a mudar.",
  why:"Encerrar aqui respeita o fato de que você já deu um feedback claro: repetir pode sugerir que você não confia que ele entendeu. O risco é que o último comentário dele indica que ele ainda não ligou os pontos, e você está escolhendo não verificar."},
 {l:"Ir ao específico (situação, comportamento, impacto) e manter a posição mesmo depois da primeira resposta dele",
  t:"“Eu entendo que você não estava tentando desanimar ninguém, e acredito nisso. Ainda assim, o impacto aconteceu, independentemente da intenção. É sobre isso que preciso que você reflita.”",
  imm:"Mike fica em silêncio por um segundo. “Justo”, diz por fim. Não é uma virada completa, mas é alguma coisa.",
  del:"Nas semanas seguintes, Mike fica visivelmente mais cuidadoso: não é perfeito, mas está tentando.",
  why:"Separar intenção de impacto dá a Mike algo concreto com que trabalhar, em vez de algo do que se defender. O custo é uma conversa mais longa e menos confortável, que prolonga algo que ele parecia pronto para encerrar."},
 {l:"Falar do padrão sem rodeios, sem amortecer",
  t:"“Mike, isso continua acontecendo e precisa parar. Não tem meio-termo.”",
  imm:"Mike fica tenso. “Tá bom... entendi”, mais na defensiva do que reflexivo.",
  del:"A mensagem chega, tecnicamente. Mas Mike fica mais na defensiva por um tempo, sem necessariamente entender por quê.",
  why:"A franqueza elimina qualquer ambiguidade sobre a seriedade do assunto. O custo é que, sem empatia, é fácil para Mike ouvir isso como um ataque, e não como uma informação que ele pode usar."}]},

{title:"Reforçando a mensagem",
 narrative:[
  "Você quer garantir que a mudança se mantenha. Há três formas de “fixar” a mensagem. Nenhuma é uma falta de conduta, mas vale notar o que cada uma realmente ensina à equipe."],
 choices:[
 {l:"Resumir por escrito e copiar a liderança de Mike, “para ser transparente”",
  t:"Você envia um e-mail resumindo a conversa e coloca em cópia quem lidera Mike.",
  imm:"O e-mail é enviado. Mike responde com educação, mas visivelmente surpreso com quem estava em cópia.",
  del:"Mike passa a hesitar antes de aceitar qualquer conversa informal com você: ele já não sabe o que vira registro.",
  why:"Isso parece accountability, mas escalar sem avisar Mike antes transforma um momento de coaching em uma consequência surpresa: quebra a confiança de que uma conversa privada continuaria privada e ensina à equipe que falar com você em particular não é realmente particular."},
 {l:"Elogiar Mike publicamente na próxima reunião por “ouvir bem”",
  t:"Na reunião seguinte, você destaca em público como Mike “melhorou a escuta”.",
  imm:"Mike parece um pouco constrangido, mas aceita o elogio. A equipe não entende bem o contexto.",
  del:"Ninguém na equipe viu Mike errar nisso em público, então o elogio soa fabricado, e o próprio Mike não sabe bem como interpretá-lo da próxima vez.",
  why:"O elogio público parece generoso, mas fabricar um momento a partir de uma correção privada, sem avisar Mike, o expõe por algo que a equipe nunca o viu acertar, e ensina à sala que feedback é teatro, não honestidade."},
 {l:"Pedir a Alex, na frente de Mike, que confirme que as coisas estão melhores agora",
  t:"“Alex, você sente que as coisas melhoraram com o Mike?”, você pergunta, com Mike presente.",
  imm:"Alex hesita, olha para Mike e dá uma resposta vaga e positiva.",
  del:"Alex evita tocar em qualquer assunto relacionado a Mike nas semanas seguintes, mesmo quando a pergunta é feita em particular.",
  why:"Isso coloca a pessoa com menos poder na sala na posição de ter que atestar publicamente, na hora, a melhora de um colega sênior. Mesmo com um tom gentil, transforma a segurança psicológica de Alex em algo que precisa ser encenado diante de uma plateia."}]},

{title:"Fechando o ciclo",
 narrative:[
  "Um mês depois. Mike não faz uma piada depreciativa há semanas, e as interrupções praticamente pararam. Alex voltou a falar, com cautela.",
  "É um progresso real, não a perfeição, e deveria aparecer também nos resultados da equipe, não só no clima. O que fazer com isso agora é uma decisão sobre a qual líderes de fato discordam."],
 choices:[
 {l:"Manter informal: mencionar as coisas à medida que surgirem",
  t:"Você decide não formalizar nada e continuar prestando atenção como vem fazendo.",
  imm:"Nada muda no dia a dia. Mike não sente que está “em um plano”.",
  del:"O progresso se mantém em geral, embora alguns momentos pequenos passem sem ser tratados quando a sua atenção está em outro lugar.",
  why:"Manter a informalidade preserva o espírito de uma mentoria genuína, coerente com o progresso real e voluntário de Mike. A contrapartida é que isso depende inteiramente da sua atenção contínua: nada obriga você a continuar percebendo se a sua disponibilidade diminuir."},
 {l:"Colocar por escrito: uma nota curta de desenvolvimento com data de acompanhamento",
  t:"Você redige algumas linhas resumindo o padrão, o progresso e uma data de acompanhamento, e compartilha diretamente com Mike.",
  imm:"Mike lê com atenção. “Entendo por que você está registrando isso. Só não esperava que fosse... oficial.”",
  del:"As expectativas agora são inequívocas para os dois, mas a relação muda um pouco: da mentoria para algo mais próximo de um processo.",
  why:"A documentação cria um registro claro e justo, que protege tanto Mike quanto Alex se algo voltar a aparecer. O custo é que formalizar antes do que Mike considera justificado pode ser lido como uma escalada e esfriar uma relação que estava indo na direção certa."},
 {l:"Considerar resolvido e seguir em frente",
  t:"Diante da melhora visível, você decide não voltar ao assunto, a menos que surja algo novo.",
  imm:"Nada é dito. Todo mundo segue em frente, inclusive você.",
  del:"Alguns meses depois, uma versão mais discreta do padrão original reaparece, desta vez com outra pessoa júnior da equipe.",
  why:"Progresso real merece reconhecimento, e reabrir o tempo todo um assunto resolvido tem o seu próprio custo. O risco, já que você viu esse padrão reaparecer discretamente uma vez, é tratar “melhor” como se fosse o mesmo que “resolvido”."}]}
],
profiles:{
 champion:{name:"Referência em segurança psicológica",
  sum:"Você interveio de forma consistente, com respeito, coragem e especificidade, mesmo quando era desconfortável. É mais provável que a sua equipe fale, discorde e assuma riscos por causa da forma como você respondeu.",
  str:"Feedback direto e específico. Equilibra empatia com accountability. Dá continuidade ao longo do tempo.",
  risk:"Atenção ao desgaste: iniciar conversas difíceis de forma constante consome energia de verdade."},
 inconsistent:{name:"Inclusão com inconsistências",
  sum:"Você se importa com inclusão, mas as suas respostas foram desiguais: às vezes corajosas e específicas, outras vezes evasivas ou vagas. É provável que a sua equipe viva a segurança como algo que depende da situação.",
  str:"Cuidado genuíno com a equipe. Capacidade de intervir com força quando você se compromete.",
  risk:"A inconsistência pode confundir mais do que um padrão consistentemente mais baixo."},
 avoider:{name:"Tendência a evitar conflitos",
  sum:"Você tende a priorizar o conforto em vez da intervenção direta. Questões que você percebeu muitas vezes ficaram sem tratamento, ou foram tratadas com suavidade demais.",
  str:"Presença acolhedora e de baixo conflito.",
  risk:"Evitar tem um custo: sem intervenção, as vozes dominantes vão abafando as outras em silêncio."},
 silencer:{name:"Silenciamento não intencional",
  sum:"Apesar das boas intenções, as suas escolhas (rir junto, ficar em silêncio, suavizar o feedback) provavelmente reforçaram as mesmas dinâmicas que desestimulam a participação. É uma das falhas mais comuns e menos visíveis, e vem de pessoas que nunca quiseram causar dano.",
  str:"Sem malícia nem agressividade: um padrão realmente corrigível quando se torna visível.",
  risk:"As pessoas da equipe podem se desengajar em silêncio em vez de confrontar você, já que nada do que você fez foi abertamente errado."}
},
plan:{
 CONT:{
  inclusion:"Abrir espaço para que as vozes mais novas ou mais quietas concluam o raciocínio.",
  engage:"Levar energia e confiança para as conversas difíceis, em vez de deixá-las esfriar.",
  develop:"Dar feedback específico e acionável, não apenas emocional.",
  results:"Conectar a segurança psicológica a decisões técnicas melhores e mais rápidas.",
  accountability:"Nomear comportamentos específicos diretamente com a pessoa responsável.",
  grow:"Manter a curiosidade sobre os seus próprios pontos cegos."},
 START:{
  inclusion:"Convidar ativamente as pessoas mais quietas da equipe a voltar para a conversa.",
  engage:"Usar a tensão como oportunidade para construir confiança, e não só para atravessá-la.",
  develop:"Estruturar o feedback com situação, comportamento e impacto.",
  results:"Medir se o silêncio de alguém está custando qualidade ou velocidade à equipe.",
  accountability:"Tratar padrões repetidos, e não apenas incidentes isolados, como algo que vale a pena nomear diretamente.",
  grow:"Perguntar a um par de confiança o que você pode estar deixando de ver sobre o seu impacto."},
 COMMIT:{
  inclusion:"Na próxima reunião de equipe, vou notar quem não falou e convidar essa pessoa pelo nome.",
  engage:"Na próxima conversa difícil, vou nomear o que a pessoa faz bem antes de nomear o que precisa mudar.",
  develop:"Nesta semana, vou dar um feedback usando situação, comportamento e impacto.",
  results:"Nesta semana, vou perguntar à equipe se algum silêncio recente pode ter nos custado uma decisão melhor.",
  accountability:"Nesta semana, vou nomear um padrão que venho deixando passar, diretamente com a pessoa envolvida.",
  grow:"Neste mês, vou perguntar a uma pessoa de confiança o que ela acha que eu não percebo sobre como me apresento nas reuniões."},
 DISC:{
  inclusion:"Que hábito concreto tornaria mais fácil para uma voz mais quieta se manifestar neste mês?",
  engage:"Quando a tensão aparece, o que você poderia fazer para que continue sendo um diálogo, e não um sermão ou um recuo?",
  develop:"Como seria dar feedback estruturado toda semana, mesmo em momentos pequenos?",
  results:"Que decisão da sua equipe poderia ter sido melhor se alguém tivesse se sentido em segurança para discordar antes?",
  accountability:"Que padrão você vem deixando passar porque nomeá-lo parecia constrangedor, e como seria nomeá-lo?",
  grow:"A quem você poderia perguntar, neste mês, o que essa pessoa acha que você não percebe sobre o seu próprio impacto na sala?"}
}
};
