module.exports={
ui:{
 docTitle:"The Mike Case: o que eu faço como par?",
 brand:"Como par",
 introTag:"Uma simulação para integrantes da equipe",
 introTitle:"The Mike Case: e se não é você quem lidera?",
 introLead:"Você não lidera a equipe. Mas estava na sala quando Mike, um colega sênior, tornou sem querer mais difícil que a voz de Alex fosse ouvida. A segurança psicológica não depende só de quem tem um cargo: também depende do que os pares fazem, ou deixam de fazer.",
 fwNote:"Mesmo sem autoridade formal, as suas escolhas são avaliadas com base no mesmo adidas Leadership Framework. A segurança psicológica afeta o desempenho da equipe, então <b>Deliver Results</b> também conta aqui.",
 introFoot:"5 decisões, mais rápida do que a versão de liderança. A maioria não tem uma opção claramente perfeita.",
 resultNote:"Seu perfil vem do seu desempenho nos seis pilares abaixo: a segurança psicológica é algo que qualquer colega pode fortalecer ou enfraquecer, com ou sem um cargo de liderança.",
 planTitle:"Seu plano de ação como par"
},
excel:[
 {w:"Conecta o trabalho do dia a dia ao propósito, aos produtos, aos consumidores e à cultura da adidas, nas ações e não só nas palavras.",a:"Eu sinto mais conexão com a adidas por causa da forma como as pessoas ao meu redor se apresentam?"},
 {w:"Assume de verdade a responsabilidade pelos resultados, equilibrando o impacto nas pessoas e no negócio.",a:"Eu assumo a responsabilidade pelos resultados mesmo quando é desconfortável, mesmo sem um cargo?"},
 {w:"Olha para a frente, questiona a forma habitual de fazer as coisas e abre espaço para soluções melhores.",a:"Estou ajudando a equipe a olhar para a frente, ou só reagindo ao que está diante de nós?"}
],
scored:{
 inclusion:"Ajuda a criar um ambiente em que diferentes perspectivas são genuinamente valorizadas e incluídas.",
 engage:"Traz uma energia e uma clareza que ajudam as pessoas ao seu redor a fazer o seu melhor trabalho.",
 develop:"Apoia ativamente o crescimento de um colega com feedback honesto e específico.",
 results:"Ajuda a transformar boas ideias em resultados ao abrir espaço para que sejam ouvidas.",
 accountability:"Nomeia os problemas de forma construtiva em vez de deixá-los passar, mesmo sem autoridade formal.",
 grow:"Mantém a abertura ao feedback e a curiosidade sobre os próprios pontos cegos."
},
phases:[
{title:"Você estava na sala",
 narrative:[
  "Você não lidera a equipe. Mas estava na reunião quando Mike descartou, rindo, a ideia de Alex (<em>“na verdade, a gente já tentou isso anos atrás, acho que toda pessoa nova precisa redescobrir os nossos velhos erros”</em>) e viu que Alex não falou mais nada até o fim da reunião.",
  "Ninguém mais parece ter notado, ou talvez tenham notado e decidido não agir. Você não tem um cargo de liderança aqui, mas está claro que isso afetou Alex.",
  "Você tem uma janela curta, ainda dentro da reunião, para decidir se faz alguma coisa."],
 choices:[
 {l:"Apoiar a ideia de Alex ali mesmo, sem confrontar Mike diretamente",
  t:"“Na verdade, acho que tem algo aqui. Alex, pode contar mais sobre como isso teria ajudado com o problema do mês passado?”",
  imm:"A conversa volta para a ideia de Alex, sem nomear o comentário de Mike. Alex parece continuar com um pouco mais de tranquilidade.",
  del:"Alex se lembra de que alguém trouxe a ideia de volta à mesa, mas o comentário de Mike em si nunca foi nomeado por ninguém.",
  why:"Isso devolve espaço a Alex sem transformar a reunião em um confronto que não cabe a você conduzir: uma forma real de agir sem autoridade formal. O custo é que o padrão em si fica sem nome, e por isso é mais fácil que se repita."},
 {l:"Ficar em silêncio na reunião, mas falar com Alex em particular depois",
  t:"Você não diz nada na hora. Mais tarde, manda uma mensagem para Alex: “Vi o que aconteceu hoje. A sua ideia fez sentido para mim.”",
  imm:"Alex responde com um “valeu” breve, mas que soa genuíno.",
  del:"Alex sabe que pelo menos uma pessoa percebeu. Mas ninguém na sala viu isso acontecer, então a norma do grupo não muda.",
  why:"Uma demonstração de apoio em particular é real e de baixo risco: um bom primeiro passo se você não quer expor Alex ainda mais. O custo é que ela é invisível para o restante da equipe, que continua sem saber que aquele comentário incomodou alguém."},
 {l:"Presumir que a liderança vai notar e resolver: não é o seu papel consertar isso",
  t:"Você conclui que intervir não cabe a você; a sua liderança está na sala e pode notar sem ajuda.",
  imm:"A reunião continua. Ninguém mais comenta.",
  del:"Semanas depois, você percebe que Alex quase não fala mais nas reuniões, e não consegue dizer se alguém, a começar por você, fez alguma coisa a respeito.",
  why:"É verdade que corrigir publicamente um colega não é tarefa de quem não conduz a reunião: essa hesitação é razoável. Mas a segurança psicológica não depende só de quem tem um cargo: esperar que outra pessoa aja também é uma escolha, e tem um custo."}]},

{title:"Mike interrompe de novo",
 narrative:[
  "Duas semanas depois, Mike corta Alex no meio da explicação, de novo. A sugestão dele nem está errada, mas é a segunda vez neste mês. A sua liderança está na reunião e não reage.",
  "Você é par de Alex, não lidera Mike. Ainda assim, o que você faz nos próximos segundos define o que a sala aprende que é normal."],
 choices:[
 {l:"Intervir, de leve, como par",
  t:"“Espera, deixa Alex terminar. Acho que tem mais ali.”",
  imm:"Mike para. “Foi mal”, diz. Alex conclui o ponto.",
  del:"Alex percebe que alguém além da liderança notou e agiu. Depois, Mike também fica um pouco mais cuidadoso com você.",
  why:"Um par intervir, e não só quem lidera, envia um sinal forte de que isso não depende só de quem tem um cargo. O risco é parecer que você está corrigindo em público um colega sênior, o que nem todo mundo na sala vai ver com bons olhos."},
 {l:"Deixar passar, mas perguntar a Alex se quer apoio para levar o assunto à liderança",
  t:"Depois da reunião: “Percebi que o Mike te cortou de novo. Quer que eu fale com a nossa liderança junto com você, ou prefere resolver do seu jeito?”",
  imm:"Para Alex é um alívio que alguém tenha notado, mas há hesitação: “Não sei se quero transformar isso em uma questão.”",
  del:"A decisão fica, corretamente, com Alex, mas o padrão continua acontecendo enquanto a decisão não vem.",
  why:"Perguntar a Alex, em vez de decidir em seu nome, respeita a autonomia da pessoa mais afetada: exatamente o tipo de apoio que qualquer par pode oferecer. O custo é que a solução pode demorar mais enquanto o padrão continua se repetindo."},
 {l:"Mandar uma mensagem direto para a liderança, sem falar antes com Alex",
  t:"Depois da reunião, você escreve para a sua liderança: “Percebi que o Mike cortou Alex de novo, achei que você deveria saber.”",
  imm:"A sua liderança agradece o aviso. Alex não sabe que essa conversa aconteceu.",
  del:"Se Alex descobrir depois, pode sentir que a sua situação virou assunto de outra pessoa sem nenhuma consulta, mesmo com boa intenção da sua parte.",
  why:"Avisar a liderança é uma atitude legítima e pode acelerar uma correção real. O custo é decidir isso sem incluir Alex, que provavelmente é quem mais tem a dizer sobre como e quando a própria situação é levantada."}]},

{title:"Falando você mesmo com Mike",
 narrative:[
  "Você decide que o padrão está claro o bastante para que Mike ouça isso diretamente de um par, e não só da liderança. Você está avaliando o tom e o contexto: algo justo, respeitoso e que realmente chegue até ele.",
  "Cada opção que você está considerando tem uma armadilha, embora nenhuma pareça claramente errada."],
 choices:[
 {l:"Publicar um lembrete geral no canal da equipe, sem citar o nome dele",
  t:"“Lembrete amigável: vamos garantir que as pessoas concluam o raciocínio antes de entrarmos na conversa. Vale para todo mundo :)”, você publica no canal da equipe.",
  imm:"Algumas pessoas reagem com um joinha. Mike não responde nada.",
  del:"Como foi dirigido a todo mundo, Mike pode razoavelmente presumir que não era com ele, e o padrão específico com Alex fica sem tratamento.",
  why:"Um lembrete público e geral evita apontar alguém, o que pode parecer a opção mais justa e de menor risco. O custo é que um feedback vago e dirigido a todo mundo permite que a única pessoa a quem ele realmente se refere não se sinta incluída, e não faz nada por Alex, que viu tudo acontecer e sabe exatamente de quem se tratava."},
 {l:"Dizer a ele que “algumas pessoas perceberam”, sem dizer quem",
  t:"“Ei, algumas pessoas perceberam que você corta o pessoal nas reuniões. Talvez valha a pena prestar atenção.”",
  imm:"Mike é pego de surpresa. “Quem disse isso?”, pergunta. Você não responde.",
  del:"Mike passa os dias seguintes se perguntando quem está falando dele pelas costas, mais focado nisso do que no comportamento em si.",
  why:"Citar “algumas pessoas” pode parecer dar mais peso e protege qualquer pessoa de ser identificada como a fonte. Mas invocar um coletivo anônimo faz o feedback parecer vir de todo lugar e de lugar nenhum: fica difícil para Mike lidar com ele de verdade, e pode soar como um ataque em grupo, e não como um feedback honesto e assumido por alguém."},
 {l:"Tocar no assunto de forma casual no happy hour da equipe, para parecer menos sério",
  t:"Nos drinks depois do trabalho, você comenta de leve: “Haha, hoje você calou Alex mesmo, hein?”",
  imm:"Mike ri na hora: “É, é, foi mal.” A conversa muda de assunto imediatamente.",
  del:"Como foi dito em tom de piada em um contexto social, Mike não registra isso como feedback, e nada muda.",
  why:"Um momento casual e social pode parecer a forma menos confrontadora de levantar algo, e às vezes funciona melhor do que uma conversa formal. O custo é que embrulhar um feedback real em uma piada, em um espaço que implicitamente está fora do trabalho, torna fácil para a outra pessoa não levar a sério, e mistura uma conversa corretiva em um espaço que deveria estar livre disso."}]},

{title:"Tentando ajudar",
 narrative:[
  "Você finalmente decide falar com Alex sobre tudo isso. As suas intenções são boas, mas as três formas mais fáceis de abrir essa conversa têm um problema em comum, embora nenhuma pareça errada à primeira vista."],
 choices:[
 {l:"Minimizar, para tranquilizar",
  t:"“Não se preocupe, o Mike é assim com todo mundo, não é pessoal.”",
  imm:"Alex concorda com a cabeça, mas não parece sentir mais alívio: só vontade de encerrar o assunto.",
  del:"Alex aprende que levantar isso de novo provavelmente vai receber um “não é nada demais”, o que desestimula trazer o assunto se acontecer outra vez.",
  why:"Isso parece reconfortante e tenta aliviar o momento: uma intenção genuína. Mas minimizar invalida a experiência de Alex antes mesmo de você ter ouvido de verdade: decidir que “não é pessoal” não é uma decisão que cabe a você tomar em seu lugar."},
 {l:"Colocar no centro uma experiência parecida sua",
  t:"“Ah, eu sei exatamente como é, ele faz isso comigo também, uma vez...”, e você continua com a sua própria história.",
  imm:"Alex ouve com educação, mas quase não consegue voltar ao próprio assunto.",
  del:"Alex sai da conversa com a sensação de que veio desabafar e acabou ouvindo a experiência de outra pessoa.",
  why:"Compartilhar uma experiência parecida pode criar uma conexão genuína e mostrar a Alex que isso não acontece só com uma pessoa. O problema é quando ela toma conta do espaço: a segurança psicológica de Alex depende de ter a sua voz ouvida, não de você sentir compreensão."},
 {l:"Oferecer-se para resolver no lugar de Alex, sem perguntar antes",
  t:"“Deixa comigo, eu vou falar com o Mike sobre isso diretamente.”",
  imm:"Alex diz “tá bom”, com um pouco de incerteza, sem ter pedido isso.",
  del:"Se a conversa com Mike não for bem, Alex pode ficar no meio de uma tensão que não escolheu, e sem nenhuma consulta sobre como queria que a própria situação fosse tratada.",
  why:"Oferecer-se para tomar uma ação concreta vem de um cuidado real, e às vezes é exatamente o que alguém quer. O problema é presumir isso sem perguntar: tira de Alex a escolha sobre se e como a sua situação é tratada por outra pessoa."}]},

{title:"Quando (e como) escalar",
 narrative:[
  "O padrão com Mike continua, semana após semana. Alex ainda não levantou o assunto formalmente. Você percebe que isso também está custando à equipe: boas ideias não chegam à mesa, e algumas decisões técnicas ficam mais lentas ou piores sem a contribuição de Alex.",
  "Há mais de uma forma razoável de levar isso adiante, e cada uma tem um custo diferente."],
 choices:[
 {l:"Levantar o assunto agora, com o que você viu, mesmo sem Alex pedir",
  t:"Você marca um horário com a sua liderança e descreve o padrão que observou, deixando claro que é a sua própria leitura, não a de Alex.",
  imm:"A sua liderança agradece e diz que vai prestar mais atenção.",
  del:"Algo muda mais rápido, mas Alex pode se surpreender ao saber que a sua situação foi levantada sem que tenha escolhido o momento.",
  why:"Agir a partir do que você viu, com transparência de que é a sua própria leitura, é uma forma legítima de evitar que um padrão real espere demais, e se conecta diretamente à qualidade das decisões da equipe. O custo é decidir o momento por Alex, mesmo com boa intenção."},
 {l:"Esperar um padrão ainda mais claro antes de levar isso a algum lugar",
  t:"Você decide que ainda não tem certeza suficiente e prefere continuar observando por mais um tempo.",
  imm:"Nada muda no curto prazo.",
  del:"O padrão se repete mais uma vez, de forma parecida, antes que alguém diga alguma coisa.",
  why:"Querer certeza antes de agir é uma forma genuína de cuidado e evita alarmes falsos. O risco é que você já viu esse padrão se repetir mais de uma vez: esperar que fique “ainda mais claro” pode virar uma forma de adiar indefinidamente."},
 {l:"Usar um canal indireto: uma pesquisa de engajamento ou uma ferramenta de feedback anônimo",
  t:"Você registra o que observou no canal de feedback anônimo da empresa, sem citar pessoas específicas.",
  imm:"Fica registrado, sem expor ninguém diretamente.",
  del:"Pode demorar mais para virar uma ação concreta, e não está claro se alguém vai relacionar esse registro à situação de Alex.",
  why:"Um canal indireto é uma ferramenta real quando uma conversa direta parece arriscada demais, e não exige que ninguém se exponha. O custo é a velocidade, e a chance de o sinal se perder entre outros registros."}]}
],
profiles:{
 champion:{name:"Apoio consistente à segurança psicológica",
  sum:"Mesmo sem um cargo de liderança, você agiu de forma consistente, respeitosa e específica, protegendo o espaço de quem tinha menos poder na sala, mesmo quando tecnicamente não era o seu trabalho.",
  str:"Percebe os padrões cedo. Age com cuidado pela autonomia da outra pessoa. Não espera passivamente por quem tem o cargo.",
  risk:"Atenção para não assumir o papel de “resolver” pelos outros: pergunte antes de agir em nome de alguém."},
 inconsistent:{name:"Boas intenções, apoio inconsistente",
  sum:"Você se importa, mas as suas respostas variaram: às vezes um apoio real e cuidadoso, outras vezes evasão ou fazer o momento girar em torno de você.",
  str:"Cuidado genuíno com colegas.",
  risk:"A inconsistência pode confundir quem precisa de um apoio previsível, e não ocasional."},
 avoider:{name:"Observação cautelosa",
  sum:"Você tende a esperar que a liderança formal resolva as coisas, mesmo quando percebe que algo está errado. É compreensível, não é o seu cargo, mas tem um custo real para a pessoa afetada.",
  str:"Respeita a hierarquia e evita passar dos limites.",
  risk:"O silêncio pode ser lido como concordância, mesmo sem querer."},
 silencer:{name:"Reforço não intencional",
  sum:"As suas escolhas (minimizar, colocar-se no centro, agir sem perguntar) provavelmente tornaram mais difícil, sem querer, que Alex sentisse uma escuta real. Isso é comum entre colegas bem-intencionados.",
  str:"Desejo real de ajudar.",
  risk:"Boas intenções não garantem que a pessoa afetada sinta apoio."}
},
plan:{
 CONT:{
  inclusion:"Devolver a palavra a colegas que falam menos quando você percebe o espaço se fechando.",
  engage:"Levar leveza e confiança para os momentos tensos entre colegas.",
  develop:"Oferecer um apoio específico, e não apenas genérico, a quem precisa.",
  results:"Perceber quando o silêncio de um colega pode estar custando qualidade à equipe.",
  accountability:"Nomear os padrões, mesmo sem um cargo, em vez de esperar por quem tem um.",
  grow:"Perguntar antes de agir em nome de outra pessoa."},
 START:{
  inclusion:"Convidar ativamente colegas que falam menos a voltar para a conversa.",
  engage:"Usar a tensão como oportunidade de conexão, e não só como um desconforto a evitar.",
  develop:"Oferecer apoio concreto perguntando do que a pessoa realmente precisa.",
  results:"Conectar o seu apoio a decisões técnicas melhores para a equipe.",
  accountability:"Levantar padrões repetidos, mesmo quando formalmente não é o seu papel.",
  grow:"Perguntar a um colega de confiança se o seu jeito de ajudar realmente ajuda."},
 COMMIT:{
  inclusion:"Na próxima reunião, vou notar quem parou de falar e trazer essa pessoa de volta para a conversa.",
  engage:"Da próxima vez que um colega passar por algo difícil, vou perguntar como apoiar antes de agir.",
  develop:"Nesta semana, vou oferecer a um colega um apoio específico, não genérico.",
  results:"Nesta semana, vou notar se algum silêncio na equipe pode estar nos custando uma decisão melhor.",
  accountability:"Nesta semana, vou nomear um padrão que venho deixando passar, mesmo que formalmente não seja o meu papel.",
  grow:"Neste mês, vou perguntar a um colega se o meu jeito de apoiar realmente ajuda."},
 DISC:{
  inclusion:"Que hábito concreto ajudaria um colega que fala menos a sentir que tem o convite para participar?",
  engage:"Como você diferencia apoiar alguém de centrar a conversa em você?",
  develop:"Como você poderia praticar perguntar “como posso ajudar?” antes de agir em nome de alguém?",
  results:"Que decisão da sua equipe poderia ter sido melhor se alguém tivesse se sentido em segurança para falar antes?",
  accountability:"Que padrão entre colegas você vem deixando passar porque “formalmente não é o seu trabalho”?",
  grow:"A quem você poderia perguntar se o seu jeito de apoiar as pessoas é realmente útil?"}
}
};
