module.exports={
ui:{
 docTitle:"The Mike Case: ¿qué hago como par?",
 brand:"Como par",
 introTag:"Una simulación para integrantes del equipo",
 introTitle:"The Mike Case: ¿y si no eres tú quien lidera?",
 introLead:"No eres quien lidera el equipo. Pero estabas en la sala cuando Mike, un colega senior, hizo sin querer que fuera más difícil que se escuchara a Alex. La seguridad psicológica no depende solo de quién tiene un cargo: también depende de lo que hacen, o no hacen, los pares.",
 fwNote:"Incluso sin autoridad formal, tus decisiones se evalúan según el mismo adidas Leadership Framework. La seguridad psicológica afecta el desempeño del equipo, así que <b>Deliver Results</b> también cuenta aquí.",
 introFoot:"5 decisiones, más rápida que la versión de liderazgo. La mayoría no tiene una opción claramente perfecta.",
 resultNote:"Tu perfil surge de tu desempeño en los seis pilares de abajo: la seguridad psicológica es algo que cualquier colega puede fortalecer o debilitar, con o sin un cargo de liderazgo.",
 planTitle:"Tu plan de acción como par"
},
excel:[
 {w:"Conecta el trabajo cotidiano con el propósito, los productos, los consumidores y la cultura de adidas, en las acciones y no solo en las palabras.",a:"¿Siento más conexión con adidas por la forma en que se muestran las personas que me rodean?"},
 {w:"Se hace cargo de verdad de los resultados, equilibrando el impacto en las personas y en el negocio.",a:"¿Me hago cargo de los resultados incluso cuando es incómodo, incluso sin un cargo?"},
 {w:"Mira hacia adelante, cuestiona la forma habitual de hacer las cosas y abre espacio para mejores soluciones.",a:"¿Estoy ayudando al equipo a mirar hacia adelante, o solo reacciono a lo que tenemos enfrente?"}
],
scored:{
 inclusion:"Ayuda a crear un entorno donde las distintas perspectivas se valoran e incluyen de verdad.",
 engage:"Aporta una energía y una claridad que ayudan a quienes te rodean a hacer su mejor trabajo.",
 develop:"Apoya activamente el crecimiento de un colega con feedback honesto y específico.",
 results:"Ayuda a convertir buenas ideas en resultados al abrir espacio para que se escuchen.",
 accountability:"Nombra los problemas de forma constructiva en lugar de dejarlos pasar, incluso sin autoridad formal.",
 grow:"Mantiene la apertura al feedback y la curiosidad sobre sus propios puntos ciegos."
},
phases:[
{title:"Estabas en la sala",
 narrative:[
  "No eres quien lidera el equipo. Pero estabas en la reunión cuando Mike descartó entre risas la idea de Alex (<em>“en realidad eso ya lo probamos hace años, supongo que cada persona nueva tiene que redescubrir nuestros viejos errores”</em>) y viste que Alex no volvió a hablar en el resto de la reunión.",
  "Nadie más parece haberlo notado, o quizás lo notaron y decidieron no actuar. Aquí no tienes un cargo de liderazgo, pero está claro que a Alex le afectó.",
  "Tienes una ventana corta, todavía dentro de la reunión, para decidir si haces algo."],
 choices:[
 {l:"Apoyar la idea de Alex ahí mismo, sin confrontar a Mike directamente",
  t:"“En realidad, creo que aquí hay algo. Alex, ¿puedes contar más sobre cómo esto habría ayudado con el problema del mes pasado?”",
  imm:"La conversación vuelve a la idea de Alex, sin nombrar el comentario de Mike. Alex parece continuar con un poco más de comodidad.",
  del:"Alex recuerda que alguien volvió a poner la idea sobre la mesa, pero el comentario de Mike nunca fue nombrado por nadie.",
  why:"Esto le devuelve espacio a Alex sin convertir la reunión en una confrontación que no te corresponde liderar: una forma real de actuar sin autoridad formal. El costo es que el patrón en sí queda sin nombrar, y por eso es más fácil que se repita."},
 {l:"Quedarte en silencio en la reunión, pero hablar con Alex en privado después",
  t:"No dices nada en el momento. Más tarde, le escribes a Alex: “Vi lo que pasó hoy. Tu idea me pareció razonable.”",
  imm:"Alex responde con un “gracias” breve, pero que suena genuino.",
  del:"Alex sabe que al menos una persona lo notó. Pero nadie en la sala lo vio, así que la norma del grupo no cambia.",
  why:"Una muestra de apoyo en privado es real y de bajo riesgo: un buen primer paso si no quieres exponer más a Alex. El costo es que resulta invisible para el resto del equipo, que sigue sin saber que ese comentario le molestó a alguien."},
 {l:"Asumir que tu manager lo va a notar y lo va a manejar: no es tu rol resolverlo",
  t:"Piensas que intervenir no te corresponde; tu manager está en la sala y puede notarlo sin ayuda.",
  imm:"La reunión continúa. Nadie más comenta.",
  del:"Semanas después, notas que Alex casi no habla en las reuniones, y no puedes decir si alguien, empezando por ti, hizo algo al respecto.",
  why:"Es cierto que corregir públicamente a un colega no es tarea de quien no conduce la reunión: esa duda es razonable. Pero la seguridad psicológica no depende solo de quién tiene un cargo: esperar a que actúe otra persona también es una decisión, y tiene un costo."}]},

{title:"Mike interrumpe otra vez",
 narrative:[
  "Dos semanas después, Mike interrumpe a Alex en plena explicación, otra vez. Su sugerencia ni siquiera es incorrecta, pero es la segunda vez este mes. Tu manager está en la reunión y no reacciona.",
  "Eres par de Alex, no manager de Mike. Aun así, lo que hagas en los próximos segundos define qué aprende la sala que es normal."],
 choices:[
 {l:"Intervenir, con suavidad, como par",
  t:"“Espera, deja que Alex termine. Creo que hay más ahí.”",
  imm:"Mike se detiene. “Culpa mía”, dice. Alex termina su punto.",
  del:"Alex nota que alguien más, aparte de tu manager, se dio cuenta y actuó. Después, Mike también es un poco más cuidadoso contigo.",
  why:"Que intervenga un par, y no solo quien lidera, envía una señal fuerte de que esto no depende solo de quién tiene un cargo. El riesgo es que puede parecer que estás corrigiendo en público a un colega senior, algo que no todos en la sala van a leer bien."},
 {l:"Dejarlo pasar, pero preguntarle a Alex si quiere apoyo para plantearlo con tu manager",
  t:"Después de la reunión: “Noté que Mike te interrumpió otra vez. ¿Quieres que se lo mencione a nuestro manager contigo, o prefieres manejarlo a tu manera?”",
  imm:"A Alex le alivia que alguien lo haya notado, pero duda: “No sé si quiero hacer de esto un tema.”",
  del:"La decisión queda, correctamente, en manos de Alex, pero el patrón sigue ocurriendo mientras decide.",
  why:"Preguntarle a Alex, en lugar de decidir en su nombre, respeta la autonomía de la persona más afectada: justo el tipo de apoyo que cualquier par puede ofrecer. El costo es que la solución puede tardar más mientras el patrón se sigue repitiendo."},
 {l:"Escribirle directamente a tu manager, sin hablar antes con Alex",
  t:"Después de la reunión le escribes a tu manager: “Noté que Mike interrumpió a Alex otra vez, me pareció que debías saberlo.”",
  imm:"Tu manager te agradece el aviso. Alex no sabe que esta conversación ocurrió.",
  del:"Si Alex se entera más adelante, puede sentir que su situación se convirtió en tema de otra persona sin que le consultaran, aun con buena intención de tu parte.",
  why:"Avisarle a tu manager es una jugada legítima y puede acelerar una corrección real. El costo es decidirlo sin incluir a Alex, que probablemente es quien más tiene que decir sobre cómo y cuándo se plantea su propia situación."}]},

{title:"Decírselo tú a Mike",
 narrative:[
  "Decides que el patrón es lo bastante claro como para que Mike lo escuche directamente de un par, y no solo de quien lidera. Estás evaluando el tono y el contexto: algo justo, respetuoso y que realmente llegue.",
  "Cada opción que estás considerando tiene una trampa, aunque ninguna se vea claramente mal."],
 choices:[
 {l:"Publicar un recordatorio general en el canal del equipo, sin nombrarlo",
  t:"“Recordatorio amistoso: asegurémonos de dejar que las personas terminen sus ideas antes de intervenir. Va para todos :)”, publicas en el canal del equipo.",
  imm:"Algunas personas reaccionan con un pulgar arriba. Mike no responde nada.",
  del:"Como estaba dirigido a todos, Mike puede asumir razonablemente que no era por él, y el patrón específico con Alex queda sin abordar.",
  why:"Un recordatorio público y general evita señalar a alguien, lo que puede parecer la opción más justa y de menor riesgo. El costo es que un feedback vago y dirigido a todos le permite a la única persona a la que realmente apunta no darse por aludida, y no hace nada por Alex, que lo vio ocurrir y sabe exactamente de quién se trataba."},
 {l:"Decirle que “varias personas lo notaron”, sin decir quiénes",
  t:"“Oye, varias personas notaron que interrumpes a la gente en las reuniones. Quizás valga la pena prestarle atención.”",
  imm:"A Mike lo toma desprevenido. “¿Quién dijo eso?”, pregunta. No respondes.",
  del:"Mike pasa los días siguientes preguntándose quién habla de él a sus espaldas, más enfocado en eso que en la conducta en sí.",
  why:"Citar a “varias personas” puede parecer que le da más peso y protege a cualquiera de ser identificado como la fuente. Pero invocar a un colectivo anónimo hace que el feedback parezca venir de todas partes y de ninguna: a Mike le cuesta trabajarlo de verdad, y puede leerse como un ataque en grupo y no como un feedback honesto del que alguien se hace cargo."},
 {l:"Mencionarlo de manera casual en el after office del equipo, para que se sienta menos serio",
  t:"En unos tragos después del trabajo, lo mencionas a la ligera: “Jaja, hoy sí que callaste a Alex, ¿eh?”",
  imm:"Mike se ríe en el momento: “Sí, sí, culpa mía.” La conversación cambia de tema enseguida.",
  del:"Como se planteó como un chiste en un contexto social, Mike no lo registra como feedback en absoluto, y nada cambia.",
  why:"Un momento casual y social puede parecer la forma menos confrontativa de plantear algo, y a veces cae mejor que una conversación formal. El costo es que envolver un feedback real en un chiste, en un espacio que implícitamente está fuera del trabajo, hace fácil que la otra persona no lo tome en serio, y mezcla una conversación correctiva en un espacio que se supone libre de eso."}]},

{title:"Intentar ayudar",
 narrative:[
  "Finalmente decides hablar con Alex sobre todo esto. Tus intenciones son buenas, pero las tres formas más fáciles de abrir esta conversación comparten un problema, aunque ninguna parezca mala a primera vista."],
 choices:[
 {l:"Minimizarlo, para tranquilizar",
  t:"“No te preocupes, Mike es así con todo el mundo, no es personal.”",
  imm:"Alex asiente, pero no parece sentir más alivio: solo ganas de dejar el tema.",
  del:"Alex aprende que volver a plantearlo probablemente reciba un “no es para tanto”, lo que desalienta que lo mencione si vuelve a pasar.",
  why:"Esto se siente reconfortante y busca alivianar el momento: una intención genuina. Pero minimizar invalida la experiencia de Alex antes de que la hayas escuchado de verdad: decidir que “no es personal” no es algo que te corresponda decidir en su lugar."},
 {l:"Poner en el centro una experiencia parecida tuya",
  t:"“Uy, sé exactamente cómo se siente, a mí también me lo hace, una vez...”, y sigues con tu propia historia.",
  imm:"Alex escucha con cortesía, pero casi no llega a volver a su propio tema.",
  del:"Alex se va de la conversación con la sensación de que vino a desahogarse y terminó escuchando la experiencia de otra persona.",
  why:"Compartir una experiencia parecida puede generar conexión genuina y mostrarle a Alex que no es la única persona a la que le pasa. El problema es cuando ocupa todo el espacio: la seguridad psicológica de Alex depende de que se le escuche, no de que tú sientas comprensión."},
 {l:"Ofrecerte a resolverlo en su lugar, sin preguntar antes",
  t:"“Déjamelo a mí, voy a hablar con Mike de esto directamente.”",
  imm:"Alex dice “bueno”, con algo de duda, sin haberlo pedido.",
  del:"Si la conversación con Mike no sale bien, Alex puede quedar en medio de una tensión que no eligió, y sin que le consultaran cómo quería que se manejara su propia situación.",
  why:"Ofrecerte a tomar una acción concreta nace de un interés real, y a veces es exactamente lo que alguien quiere. El problema es asumirlo sin preguntar: le quita a Alex la decisión sobre si su situación la aborda otra persona, y cómo."}]},

{title:"Cuándo (y cómo) escalar",
 narrative:[
  "El patrón con Mike continúa, semana tras semana. Alex todavía no lo planteó formalmente. Notas que también le está costando al equipo: las buenas ideas no llegan a la mesa, y algunas decisiones técnicas son más lentas o peores sin el aporte de Alex.",
  "Hay más de una forma razonable de llevar esto adelante, y cada una tiene un costo distinto."],
 choices:[
 {l:"Plantearlo ahora, con lo que viste, aunque Alex no lo haya pedido",
  t:"Agendas un espacio con tu manager y describes el patrón que observaste, dejando claro que es tu propia lectura, no la de Alex.",
  imm:"Tu manager te agradece y dice que va a prestar más atención.",
  del:"Algo cambia más rápido, pero a Alex puede sorprenderle saber que su situación se planteó sin haber elegido el momento.",
  why:"Actuar a partir de lo que viste, con transparencia sobre que es tu propia lectura, es una forma legítima de evitar que un patrón real espere demasiado, y se conecta directamente con la calidad de las decisiones del equipo. El costo es decidir el momento por Alex, aun con buena intención."},
 {l:"Esperar un patrón todavía más claro antes de llevarlo a algún lado",
  t:"Decides que todavía no tienes suficiente certeza y prefieres seguir observando un tiempo más.",
  imm:"Nada cambia en el corto plazo.",
  del:"El patrón se repite una vez más, de forma parecida, antes de que alguien diga algo.",
  why:"Querer certeza antes de actuar es una forma genuina de cuidado y evita falsas alarmas. El riesgo es que ya viste repetirse este patrón más de una vez: esperar a que sea “todavía más claro” puede convertirse en una forma de postergar indefinidamente."},
 {l:"Usar un canal indirecto: una encuesta de engagement o una herramienta de feedback anónimo",
  t:"Registras lo que observaste en el canal de feedback anónimo de la empresa, sin nombrar a personas específicas.",
  imm:"Queda registrado, sin exponer directamente a nadie.",
  del:"Puede tardar más en convertirse en una acción concreta, y no está claro que alguien vaya a relacionar ese registro con la situación de Alex.",
  why:"Un canal indirecto es una herramienta real cuando una conversación directa resulta demasiado riesgosa, y no exige que nadie se exponga. El costo es la velocidad, y la posibilidad de que la señal se pierda entre otros registros."}]}
],
profiles:{
 champion:{name:"Apoyo consistente a la seguridad psicológica",
  sum:"Incluso sin un cargo de liderazgo, actuaste de forma consistente, respetuosa y específica, protegiendo el espacio de quien tenía menos poder en la sala, aunque técnicamente no fuera tu trabajo.",
  str:"Nota los patrones a tiempo. Actúa cuidando la autonomía de la otra persona. No espera pasivamente a quien tiene el cargo.",
  risk:"Cuidado con asumir el rol de “resolverlo” por los demás: pregunta antes de actuar en nombre de alguien."},
 inconsistent:{name:"Buenas intenciones, apoyo inconsistente",
  sum:"Te importa, pero tus respuestas variaron: a veces un apoyo real y cuidadoso, otras veces evasión o hacer que el momento girara en torno a ti.",
  str:"Interés genuino por tus colegas.",
  risk:"La inconsistencia puede confundir a alguien que necesita un apoyo predecible, no ocasional."},
 avoider:{name:"Observación cautelosa",
  sum:"Tiendes a esperar que el liderazgo formal resuelva las cosas, incluso cuando percibes que algo anda mal. Es comprensible, no es tu cargo, pero tiene un costo real para la persona afectada.",
  str:"Respeta la jerarquía y evita extralimitarse.",
  risk:"El silencio puede leerse como acuerdo, aun sin quererlo."},
 silencer:{name:"Refuerzo involuntario",
  sum:"Tus decisiones (minimizar, ponerte en el centro, actuar sin preguntar) probablemente hicieron más difícil, sin quererlo, que Alex sintiera una escucha real. Es común entre colegas con buenas intenciones.",
  str:"Deseo real de ayudar.",
  risk:"Las buenas intenciones no garantizan que la persona afectada sienta apoyo."}
},
plan:{
 CONT:{
  inclusion:"Devolverles la palabra a colegas que hablan menos cuando notas que el espacio se cierra.",
  engage:"Llevar ligereza y confianza a los momentos tensos entre colegas.",
  develop:"Ofrecer un apoyo específico, y no solo genérico, a quien lo necesita.",
  results:"Notar cuándo el silencio de un colega puede estar costándole calidad al equipo.",
  accountability:"Nombrar los patrones, incluso sin un cargo, en lugar de esperar a quien lo tiene.",
  grow:"Preguntar antes de actuar en nombre de otra persona."},
 START:{
  inclusion:"Invitar activamente a colegas que hablan menos a volver a la conversación.",
  engage:"Usar la tensión como una oportunidad de conexión, y no solo como una incomodidad a evitar.",
  develop:"Ofrecer apoyo concreto preguntando qué necesita realmente la persona.",
  results:"Conectar tu apoyo con mejores decisiones técnicas para el equipo.",
  accountability:"Plantear los patrones repetidos, incluso cuando formalmente no es tu rol.",
  grow:"Preguntarle a un colega de confianza si tu forma de ayudar realmente ayuda."},
 COMMIT:{
  inclusion:"En la próxima reunión, voy a notar quién dejó de hablar y voy a traer a esa persona de vuelta a la conversación.",
  engage:"La próxima vez que un colega pase por algo difícil, voy a preguntar cómo apoyar antes de actuar.",
  develop:"Esta semana, voy a ofrecerle a un colega un apoyo específico, no genérico.",
  results:"Esta semana, voy a notar si algún silencio en el equipo puede estar costándonos una mejor decisión.",
  accountability:"Esta semana, voy a nombrar un patrón que vengo dejando pasar, aunque formalmente no sea mi rol.",
  grow:"Este mes, voy a preguntarle a un colega si mi forma de apoyar realmente le sirve."},
 DISC:{
  inclusion:"¿Qué hábito concreto ayudaría a que un colega que habla menos sienta que tiene la invitación a participar?",
  engage:"¿Cómo distingues entre apoyar a alguien y centrar la conversación en ti?",
  develop:"¿Cómo podrías practicar preguntar “¿cómo puedo ayudar?” antes de actuar en nombre de alguien?",
  results:"¿Qué decisión de tu equipo podría haber sido mejor si alguien se hubiera sentido con seguridad para hablar antes?",
  accountability:"¿Qué patrón entre colegas vienes dejando pasar porque “formalmente no es tu trabajo”?",
  grow:"¿A quién podrías preguntarle si tu forma de apoyar a las personas es realmente útil?"}
}
};
